name: mycafeinventory
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  google_generative_ai: ^0.4.7
  flutter_svg: ^2.1.0
  firebase_core: ^3.13.1
  cloud_firestore: ^5.6.0
  firebase_auth: ^5.5.4
  sizer: ^2.0.15
  cupertino_icons: ^1.0.8
  get: ^4.6.6 
  cached_network_image: ^3.4.1
  intl: ^0.20.2
  fl_chart: ^0.71.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
