// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvq6ZocfNpjzIUZEEB0Zb-JsEcY-ru1gc',
    appId: '1:288120395867:web:152877bcf129d63e74077e',
    messagingSenderId: '288120395867',
    projectId: 'acisku-bc32f',
    authDomain: 'acisku-bc32f.firebaseapp.com',
    storageBucket: 'acisku-bc32f.firebasestorage.app',
    measurementId: 'G-HMZYSN3RWW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_nRr0Ju5YoT9wWEWARpe_8gJpR1xbvyE',
    appId: '1:288120395867:android:2b45ca426d84d48f74077e',
    messagingSenderId: '288120395867',
    projectId: 'acisku-bc32f',
    storageBucket: 'acisku-bc32f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAX_WwzAnWVMaCYzpwwDDmJpt6cjspeeDY',
    appId: '1:288120395867:ios:0e0587c166345f1e74077e',
    messagingSenderId: '288120395867',
    projectId: 'acisku-bc32f',
    storageBucket: 'acisku-bc32f.firebasestorage.app',
    iosBundleId: 'com.example.acisku',
  );
}
