// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhlNFxq65NaTmpJGVq_M_BsadPigR-fsM',
    appId: '1:677223987423:web:f755d65b2d2e8f3e66116a',
    messagingSenderId: '677223987423',
    projectId: 'mciapp-5adfb',
    authDomain: 'mciapp-5adfb.firebaseapp.com',
    storageBucket: 'mciapp-5adfb.firebasestorage.app',
    measurementId: 'G-MT0JFWDYLK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjjAVYWEXU3iA8hyVn6XQURPbjyz9PceY',
    appId: '1:677223987423:android:2a13bfff6d78f08366116a',
    messagingSenderId: '677223987423',
    projectId: 'mciapp-5adfb',
    storageBucket: 'mciapp-5adfb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7hXxymE505rE3pmPrG0d9f-vmUynkmQc',
    appId: '1:677223987423:ios:df4dce56d13b2cbc66116a',
    messagingSenderId: '677223987423',
    projectId: 'mciapp-5adfb',
    storageBucket: 'mciapp-5adfb.firebasestorage.app',
    iosBundleId: 'com.example.acisku',
  );

}